name: Build and deploy CVAT
run-name: ${{ github.actor }} triggered Build and deploy CVAT
on:
  push:
    branches:
      - releases/*

env:
  VERSION: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set Up SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.CVAT_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
        HOST=${{ secrets.HOST }}
        USERNAME=${{ secrets.USERNAME }}

    - name: Create Directory on Server
      run: |
        ssh -i ~/.ssh/id_rsa $USERNAME@$HOST 'mkdir -p test'