name: Build and deploy CVAT
run-name: ${{ github.actor }} triggered Build and deploy CVAT
on:
  push:
    branches:
      - releases/*

env:
  VERSION: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.CVAT_PRIVATE_KEY }}

    - name: Copy cvat to volumes
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.CVAT_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        timeout: '120s'
        source: "*"
        target: ../../volumes/cvat_new

    - name: Executing remote ssh commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.CVAT_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ../../volumes/cvat_new
          ls